namespace Attendance_Management_System.Models
{
    /// <summary>
    /// Represents one QR code session generated by a teacher for a specific class.
    /// Each session has a unique token, an expiry time, and tracks who already scanned.
    /// </summary>
    public class QRSession
    {
        public int Id { get; set; }

        public int CourseId { get; set; }

        /// <summary>
        /// The unique random token embedded in the QR code.
        /// This is what the student's device sends when they scan.
        /// </summary>
        public string Token { get; set; } = string.Empty;

        public DateOnly Date { get; set; }

        /// <summary>
        /// When this QR code was generated.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When this QR code stops being valid.
        /// Set to CreatedAt + ValidForMinutes at generation time.
        /// </summary>
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Teacher can manually deactivate the QR before it expires.
        /// </summary>
        public bool IsActive { get; set; } = true;

        // Navigation
        public Course Course { get; set; } = null!;

        /// <summary>
        /// Tracks which students already scanned this session.
        /// Prevents double-scanning.
        /// </summary>
        public ICollection<QRScan> Scans { get; set; } = new List<QRScan>();
    }

    /// <summary>
    /// Records each individual student scan of a QR session.
    /// One row = one student scanned once.
    /// </summary>
    public class QRScan
    {
        public int Id { get; set; }

        public int QRSessionId { get; set; }

        public int StudentId { get; set; }

        public DateTime ScannedAt { get; set; } = DateTime.UtcNow;

        // Navigation
        public QRSession QRSession { get; set; } = null!;
        public Student Student { get; set; } = null!;
    }
}